version: '3.8'
services: 
  db:
    container_name: postgres_db_fastapi
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - database_postgres:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    networks:
      - fastapi
  app:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - ./:/code
    depends_on:
      - db
    networks:
      - fastapi
volumes:
  database_postgres:
networks:
  fastapi:
    driver: bridge