version: '3.8'
services: 
  app:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - ./:/code
    networks:
      - fastapi
networks:
  fastapi:
    driver: bridge